version: "3.4"

services:
  nginx-proxy:
    image: nginx:stable-alpine
    container_name: codeline_nginx
    restart: unless-stopped
    networks:
      - webproxy
      - default
    expose:
      - "80"
    environment: 
      VIRTUAL_HOST: http://178.128.118.182/
      LETSENCRYPT_HOST: http://178.128.118.182/
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - api-server
      - client

  client:
    build:
      context: ./
      dockerfile: ./client/Dockerfile.prod
    depends_on:
      - api-server
    environment:
      - NODE_ENV=production
      - CHOKIDAR_USEPOLLING=true
      - CI=true
    ports:
      - "3000:3000"
    stdin_open: true

  api-server:
    build:
      context: ./
      dockerfile: ./server/Dockerfile.prod
    environment:
      - NODE_ENV=production
      - SECRET=${SECRET}
      - DEV_DB=${DEV_DB}
      - DB_CONNECTION=
    ports:
      - "8861:8861"

networks:
  default:
    external:
      name:
        web_network
  webproxy:
    external: 
      name: webproxy
